name: ccpc
description: Hackathon App for Cloud Counselage

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_gen: ^4.1.5
  flutter_gen_runner: ^4.1.5
  flutter_modular: ^4.4.0+1
  flutter_native_splash: ^2.0.2
  flutter_screenutil: ^5.2.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.2.3
  introduction_screen: ^2.1.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans-Hebrew
      fonts:
        - asset: assets/fonts/OpenSansHebrew-Regular.ttf
        - asset: assets/fonts/OpenSansHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansHebrew-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSansHebrew-BoldItalic.ttf
          weight: 700
          style: italic
flutter_gen:
  output: lib/gen
  # Optional
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/Colors.xml
